In [ ]:
#Using the Files pane (easiest for small files):

import pandas as pd
df = pd.read_csv('insurance.csv')

In [ ]:
#programmatic Upload
from google.colab import files
uploaded = files.upload()

Saving insurance.csv to insurance (1).csv

In [ ]:
'''#Mounting Google Drive:
from google.colab import drive
drive.mount('/content/drive')'''

"#Mounting Google Drive:\nfrom google.colab import drive\ndrive.mount('/content/drive')"

In [ ]:
#df = pd.read_csv('/content/drive/MyDrive/insurance.csv')

In [ ]:
# pandas     → opens and manages data (like Excel for Python)
# numpy      → does math
# matplotlib → draws charts
# seaborn    → draws prettier charts

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print('All libraries loaded!')

All libraries loaded!

In [ ]:
# Show the first 5 rows
df.head(10)
#df.tail(10)

        age     sex       bmi  children smoker     region   charges
0 -1.438764  female -0.453320 -0.908614    yes  southwest  0.298584
1 -1.509965    male  0.509621 -0.078767     no  southeast -0.953689
2 -0.797954    male  0.383307  1.580926     no  southeast -0.728675
3 -0.441948    male -1.305531 -0.908614     no  northwest  0.719843
4 -0.513149    male -0.292556 -0.908614     no  northwest -0.776802
5 -0.584350  female -0.807656 -0.908614     no  southeast -0.785908
6  0.483668  female  0.455486 -0.078767     no  southeast -0.415500
7 -0.157143  female -0.479567  1.580926     no  northwest -0.494728
8 -0.157143    male -0.136714  0.751079     no  northeast -0.567017
9  1.480485  female -0.791252 -0.908614     no  northwest  1.293027

In [ ]:
# How many rows and columns?
print('Rows:', df.shape[0])
print('Columns:', df.shape[1])
df.shape

Rows: 1338
Columns: 7

(1338, 7)

In [ ]:
# What type of data is in each column?
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   float64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   float64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(4), object(3)
memory usage: 73.3+ KB

###age → numerical
###bmi → numerical
###charges → numerical
###sex, smoker, region → categorical variables

In [ ]:
# Basic statistics — average, min, max
df.describe()

                age           bmi      children       charges
count  1.338000e+03  1.338000e+03  1.338000e+03  1.338000e+03
mean  -1.805565e-16 -2.124194e-16 -5.576008e-17 -8.098488e-17
std    1.000374e+00  1.000374e+00  1.000374e+00  1.000374e+00
min   -1.509965e+00 -2.412011e+00 -9.086137e-01 -1.003557e+00
25%   -8.691547e-01 -7.164063e-01 -9.086137e-01 -7.046504e-01
50%   -1.474046e-02 -4.320880e-02 -7.876719e-02 -3.212089e-01
75%    8.396738e-01  6.611572e-01  7.510793e-01  2.783441e-01
max    1.765289e+00  3.685522e+00  3.240619e+00  4.171663e+00

In [ ]:
# Are there any missing values (blanks)?
print(df.isnull().sum())

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

###No missing values were found in the dataset.

In [ ]:
# The 'region' column has been one-hot encoded and no longer exists.
# To see unique values of the original categorical columns before encoding, this cell would have been run earlier.
# If you want to see the new encoded columns, you can inspect `df.columns` or specific encoded columns.
print('All columns after encoding:', list(df.columns))

All columns after encoding: ['age', 'bmi', 'children', 'charges', 'region_northwest', 'region_southeast', 'region_southwest', 'sex_male', 'smoker_yes']

###Step 3: Convert Text to Numbers (Encoding)

In [ ]:
df = pd.get_dummies(df, columns=['region', 'sex', 'smoker'], drop_first=True)

print('All text converted to numbers!')
print('Columns:', list(df.columns))

KeyError: "None of [Index(['region', 'sex', 'smoker'], dtype='object')] are in the [columns]"

In [ ]:
from sklearn.preprocessing import StandardScaler

# Identify numerical features to scale
numerical_features = ['age', 'bmi', 'children', 'charges']

# Initialize StandardScaler
scaler = StandardScaler()

# Apply scaling to the numerical features
df[numerical_features] = scaler.fit_transform(df[numerical_features])

print('Numerical features scaled successfully!')
print(df.head())

Numerical features scaled successfully!
        age       bmi  children   charges  region_northwest  region_southeast  \
0 -1.438764 -0.453320 -0.908614  0.298584             False             False
1 -1.509965  0.509621 -0.078767 -0.953689             False              True
2 -0.797954  0.383307  1.580926 -0.728675             False              True
3 -0.441948 -1.305531 -0.908614  0.719843              True             False
4 -0.513149 -0.292556 -0.908614 -0.776802              True             False

   region_southwest  sex_male  smoker_yes
0              True     False        True
1             False      True       False
2             False      True       False
3             False      True       False
4             False      True       False